name: CI/CD for ASP.NET Core and React

on:
  push:
    branches:
      - main  # Adjust the branch name you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Adjust the Node.js version you require

    - name: Install Node Dependencies
      run: npm install
      working-directory: frontend  # Adjust to your React app's directory path

    - name: Build React App
      run: npm run build
      working-directory: frontend  # Adjust to your React app's directory path

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0  # Adjust the .NET Core version you require

    - name: Build and Test ASP.NET Core
      run: |
        dotnet build
        dotnet test
      working-directory: backend  # Adjust to your ASP.NET Core app's directory path

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Hosting Service
