name: ASP.NET Core CI/CD

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0  

    - name: Install Dependencies
      run: dotnet restore
      working-directory: Food 

    - name: Build and Test
      run: |
        dotnet build
        dotnet test
      working-directory: Food
